version: '3'
services:
  web:
    restart: always
    image: helloworld_dev
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/home/app/webapp/
    ports:
      - 8080:80
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dingo
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dingo
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

# TODO: implement environment specific .env