version: '3'
volumes:
  postgres_db_prod:
services:
  web:
    restart: always
    image: helloworld_prod
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    ports:
      - 8080:80
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_db_prod:/var/lib/postgresql/data

