version: '3'
volumes:
  postgres_db:
services:
  web:
    restart: always
    image: web_hellworld
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:80
    environment:
      APP_DB_DATABASE: ${POSTGRES_DB}
      APP_DB_USERNAME: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_HOST: ${POSTGRES_HOST}
      APP_DB_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data

